# Generated by Django 5.2.10 on 2026-02-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_remove_staffprofile_is_admin_staffprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='timetable',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
