# Generated by Django 5.2.10 on 2026-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_staffprofile_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='duty_count',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
    ]
