# Generated by Django 5.2.10 on 2026-02-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0004_remove_staffprofile_duty_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
