# Generated by Django 5.2.10 on 2026-03-02 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0005_alter_staffprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('room_no', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Classroom Setup',
                'verbose_name_plural': 'Classroom Setup',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedule',
            },
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duties.classroomsetup'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duties.examschedule'),
        ),
        migrations.CreateModel(
            name='StaffManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('grade', models.CharField(default='Assistant Professor', max_length=50)),
                ('timetable_data', models.JSONField(blank=True, default=list)),
                ('duty_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Management',
                'verbose_name_plural': 'Staff Management',
            },
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duties.staffmanagement'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
