# Generated by Django 5.2.10 on 2026-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0006_classroomsetup_examschedule_remove_staffprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmanagement',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
