# Generated by Django 5.2.10 on 2026-03-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0007_staffmanagement_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsetup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
