# Generated by Django 5.2.10 on 2026-03-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0008_classroomsetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmanagement',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
