# Generated by Django 5.2.10 on 2026-03-10 03:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0009_staffmanagement_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyassignment',
            options={'verbose_name': 'Duty Assignment', 'verbose_name_plural': 'Duty Assignments'},
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmanagement',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='duties.classroomsetup'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assignments', to='duties.examschedule'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_duties', to='duties.staffmanagement'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='time_slot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffmanagement',
            name='title',
            field=models.CharField(blank=True, default='Mr.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staffmanagement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffmanagement', to=settings.AUTH_USER_MODEL),
        ),
    ]
