# Generated by Django 5.2.10 on 2026-03-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0010_alter_dutyassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
