# Generated by Django 5.2.10 on 2026-03-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0011_staffmanagement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmanagement',
            name='title',
        ),
    ]
