# Generated by Django 5.2.10 on 2026-03-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0012_remove_staffmanagement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='exam_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='session',
            field=models.CharField(default='FN', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffDutyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=10)),
                ('staff_grade', models.CharField(max_length=50)),
                ('required_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Staff Duty Requirement',
                'verbose_name_plural': 'Staff Duty Requirements',
                'unique_together': {('date', 'session', 'staff_grade')},
            },
        ),
    ]
