# Generated by Django 5.2.10 on 2026-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0013_examschedule_exam_type_examschedule_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdutyrequirement',
            name='exam_type',
            field=models.CharField(default='Regular Exam', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdutyrequirement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffdutyrequirement',
            name='session',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staffdutyrequirement',
            name='staff_grade',
            field=models.CharField(max_length=100),
        ),
    ]
