# Generated by Django 5.2.10 on 2026-03-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0014_staffdutyrequirement_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmanagement',
            name='internal1_duty_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffmanagement',
            name='internal2_duty_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffmanagement',
            name='regular_duty_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffmanagement',
            name='supply_duty_count',
            field=models.IntegerField(default=0),
        ),
    ]
