# Generated by Django 5.2.10 on 2026-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0017_remove_dutyassignment_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffavailability',
            name='day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
