# Generated by Django 5.2.10 on 2026-03-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0018_staffavailability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffavailability',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='free_periods',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
