# Generated by Django 5.2.10 on 2026-03-14 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0019_alter_staffavailability_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'exam_date', 'session', 'course_name')},
        ),
    ]
