# Generated by Django 5.2.10 on 2026-03-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0020_alter_staffavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsetup',
            name='session',
            field=models.CharField(choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], default='FN', max_length=2),
        ),
    ]
