# Generated by Django 5.2.10 on 2026-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0021_classroomsetup_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsetup',
            name='session',
            field=models.CharField(default='FN', max_length=2),
        ),
    ]
