# Generated by Django 5.2.10 on 2026-03-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0022_alter_classroomsetup_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomsetup',
            name='session',
        ),
    ]
