# Generated by Django 5.2.10 on 2026-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0023_remove_classroomsetup_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsetup',
            name='exam_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Internal Test 1', 'Internal Test 1'), ('Internal Test 2', 'Internal Test 2'), ('Supplementary', 'Supplementary')], default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='classroomsetup',
            name='session',
            field=models.CharField(choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], default='FN', max_length=10),
        ),
    ]
