# Generated by Django 5.2.10 on 2026-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0024_classroomsetup_exam_type_classroomsetup_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsetup',
            name='session',
            field=models.CharField(choices=[('FN', 'FN'), ('AN', 'AN')], default='FN', max_length=10),
        ),
    ]
