# Generated by Django 5.2.10 on 2026-03-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0025_alter_classroomsetup_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyassignment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='exam_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='session',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dutyassignment',
            unique_together={('staff', 'date', 'session')},
        ),
    ]
