# Generated by Django 5.2.10 on 2026-03-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0026_dutyassignment_date_dutyassignment_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyassignment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dutyassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duties.classroomsetup'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duties.staffmanagement'),
        ),
        migrations.RemoveField(
            model_name='dutyassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dutyassignment',
            name='exam_schedule',
        ),
    ]
