# Generated by Django 5.2.10 on 2026-03-16 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0027_alter_dutyassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyassignment',
            options={'verbose_name': 'Duty Assignment', 'verbose_name_plural': 'Duty Assignments'},
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='duties.classroomsetup'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_duties', to='duties.staffmanagement'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyassignment',
            unique_together={('staff', 'date', 'session')},
        ),
    ]
