# Generated by Django 5.2.10 on 2026-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0028_alter_dutyassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
