# Generated by Django 5.2.10 on 2026-03-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0029_alter_dutyassignment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyassignment',
            options={},
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
