# Generated by Django 5.2.10 on 2026-03-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0030_alter_dutyassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmanagement',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='staffmanagement',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
