# Generated by Django 5.2.10 on 2026-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0031_remove_staffmanagement_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmanagement',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
