# Generated by Django 5.2.10 on 2026-03-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0032_alter_staffmanagement_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmanagement',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
