# Generated by Django 5.2.10 on 2026-03-18 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0033_alter_staffmanagement_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='exam_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Internal Test 1', 'Internal Test 1'), ('Internal Test 2', 'Internal Test 2'), ('Supplementary', 'Supplementary')], default='Regular', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'exam_date', 'session', 'exam_type', 'course_name')},
        ),
    ]
